### ISSUE TITLE
v1.4 feedback

### ISSUE THREAD

**Issue by eugenepeh** [CS2103JAN2018-W09-B2/main#150]
Good job on meeting the requirements for individual and team components.
@Jason1im , for your case I will be leaving it as a remark for lecturers to decide.

Everyone please remember to update your User Guide, README and release if you guys made any changes before Friday testing.

Refer to https://nus-cs2103-ay1718s2.github.io/website/admin/index.html#admin-project-v14 under `v1.4 Testing` to know what you need to do on that day.

**Comment by eugenepeh** [comment]
As promised, here's the solution to the OODM activity 
![image](https://user-images.githubusercontent.com/19277206/38285771-60fad3a6-37f4-11e8-9583-e5d1ec2eda2c.png)

**Comment by Jason1im** [comment]
@eugenepeh, thank you for helping me to inform the lecturers about my case.
